global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'app'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['app:8080']
        labels:
          group: 'application'
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          group: 'prometheus'
