server:
  port: 8080


load-generator:
  duration-minutes: ${DURATION_MINUTES:20}

backpressure-active: ${BACKPRESSURE_ACTIVE:false}

spring:
  task:
    scheduling:
      pool:
        size: 2
  kafka:
    bootstrap-servers: kafka:9092 #localhost:29092
    topic: topic
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.priority.model
        spring.json.value.default.type: com.example.priority.model.Message
        spring.json.use.type.headers: false

management:
  endpoints.web.exposure.include: health,metrics,prometheus
  metrics.distribution.percentiles-histogram.http.server.requests: true
  endpoint.prometheus.enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

  defaults:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      experiment: ${EXPERIMENT_ID:runDummy}

