server:
  port: 8080


load-generator:
  duration-minutes: ${DURATION_MINUTES:20}
  high-rate: ${HIGH_RATE:50}

backpressure:
  enabled: ${BACKPRESSURE_ENABLED:false}
  credits: ${BACKPRESSURE_CREDITS:500}
db-enabled: ${DB_ENABLED:false}

spring:
  task:
    scheduling:
      pool:
        size: 2
  datasource:
    url: jdbc:postgresql://pg:5432/postgres
    username: postgres
    password: postgres
    hikari:
      maximumPoolSize: 1
      minimumIdle: 1
      poolName: pg-pool
      connectionTimeout: 250 #ms

  sql:
    init:
      mode: always   # apply schema.sql on start
      separator: ^;
  kafka:
    bootstrap-servers: kafka:9092 #localhost:29092
    topic: topic
    producer:
      properties:
        linger.ms: 0
        batch.size: 1
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.priority.model
        spring.json.value.default.type: com.example.priority.model.Message
        spring.json.use.type.headers: false

management:
  endpoints.web.exposure.include: health,metrics,prometheus
  metrics.distribution.percentiles-histogram.http.server.requests: true
  endpoint.prometheus.enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

  defaults:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      experiment: ${EXPERIMENT_ID:runDummy}

