{
 "title": "Main",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency P99, P95, Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "latency_p99", "legendFormat": "__auto" },
    { "expr": "latency_p95", "legendFormat": "__auto" },
    { "expr": "latency_avg", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Througput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "throughput", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Backpressure Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "backpressureGate_queue_depth", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Count emitted And Handled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "count_emitted", "legendFormat": "__auto" },
    { "expr": "count_handled", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Backpressure Credits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "backpressureGate_credits", "legendFormat": "__auto" }
   ]
  }
 ]
}